// Dialog and RowData
export const SET_DIALOG = "SET_DIALOG";
export const SET_DIALOG_DELETE = "SET_DIALOG_DELETE";
export const SET_DIALOG_CERTIFICATE = "SET_DIALOG_CERTIFICATE";

//  Employee
export const SET_EMPLOYEE = "SET_EMPLOYEE";

export const GET_EMPLOYEES_REQUESTED = "GET_EMPLOYEES_REQUESTED";
export const GET_EMPLOYEES_SUCCEEDED = "GET_EMPLOYEES_SUCCEEDED";
export const GET_EMPLOYEES_FAILED = "GET_EMPLOYEES_FAILED";

export const ADD_EMPLOYEE_REQUESTED = "ADD_EMPLOYEE_REQUESTED";
export const ADD_EMPLOYEE_SUCCEEDED = "ADD_EMPLOYEE_SUCCEEDED";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_REQUESTED = "EDIT_EMPLOYEE_REQUESTED";
export const EDIT_EMPLOYEE_SUCCEEDED = "EDIT_EMPLOYEE_SUCCEEDED";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_REQUESTED = "DELETE_EMPLOYEE_REQUESTED";
export const DELETE_EMPLOYEE_SUCCEEDED = "DELETE_EMPLOYEE_SUCCEEDED";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";

// Province
export const SET_PROVINCE = "SET_PROVINCE";

export const GET_PROVINCES_REQUESTED = "GET_PROVINCES_REQUESTED";
export const GET_PROVINCES_SUCCEEDED = "GET_PROVINCES_SUCCEEDED";
export const GET_PROVINCES_FAILED = "GET_PROVINCES_FAILED";

export const ADD_PROVINCE_REQUESTED = "ADD_PROVINCE_REQUESTED";
export const ADD_PROVINCE_SUCCEEDED = "ADD_PROVINCE_SUCCEEDED";
export const ADD_PROVINCE_FAILED = "ADD_PROVINCE_FAILED";

export const EDIT_PROVINCE_REQUESTED = "EDIT_PROVINCE_REQUESTED";
export const EDIT_PROVINCE_SUCCEEDED = "EDIT_PROVINCE_SUCCEEDED";
export const EDIT_PROVINCE_FAILED = "EDIT_PROVINCE_FAILED";

export const DELETE_PROVINCE_REQUESTED = "DELETE_PROVINCE_REQUESTED";
export const DELETE_PROVINCE_SUCCEEDED = "DELETE_PROVINCE_SUCCEEDED";
export const DELETE_PROVINCE_FAILED = "DELETE_PROVINCE_FAILED";

// District
export const SET_DISTRICT = "SET_DISTRICT";

export const GET_DISTRICTS_IN_PROVINCE_REQUESTED =
  "GET_DISTRICTS_IN_PROVINCE_REQUESTED";
export const GET_DISTRICTS_IN_PROVINCE_SUCCEEDED =
  "GET_DISTRICTS_IN_PROVINCE_SUCCEEDED";
export const GET_DISTRICTS_IN_PROVINCE_FAILED =
  "GET_DISTRICTS_IN_PROVINCE_FAILED";

export const GET_DISTRICTS_REQUESTED = "GET_DISTRICTS_REQUESTED";
export const GET_DISTRICTS_SUCCEEDED = "GET_DISTRICTS_SUCCEEDED";
export const GET_DISTRICTS_FAILED = "GET_DISTRICTS_FAILED";

export const ADD_DISTRICT_REQUESTED = "ADD_DISTRICT_REQUESTED";
export const ADD_DISTRICT_SUCCEEDED = "ADD_DISTRICT_SUCCEEDED";
export const ADD_DISTRICT_FAILED = "ADD_DISTRICT_FAILED";

export const EDIT_DISTRICT_REQUESTED = "EDIT_DISTRICT_REQUESTED";
export const EDIT_DISTRICT_SUCCEEDED = "EDIT_DISTRICT_SUCCEEDED";
export const EDIT_DISTRICT_FAILED = "EDIT_DISTRICT_FAILED";

export const DELETE_DISTRICT_REQUESTED = "DELETE_DISTRICT_REQUESTED";
export const DELETE_DISTRICT_SUCCEEDED = "DELETE_DISTRICT_SUCCEEDED";
export const DELETE_DISTRICT_FAILED = "DELETE_DISTRICT_FAILED";

// Ward
export const SET_WARD = "SET_WARD";

export const GET_WARDS_IN_DISTRICT_REQUESTED =
  "GET_WARDS_IN_DISTRICT_REQUESTED";
export const GET_WARDS_IN_DISTRICT_SUCCEEDED =
  "GET_WARDS_IN_DISTRICT_SUCCEEDED";
export const GET_WARDS_IN_DISTRICT_FAILED = "GET_WARDS_IN_DISTRICT_FAILED";

export const GET_WARDS_REQUESTED = "GET_WARDS_REQUESTED";
export const GET_WARDS_SUCCEEDED = "GET_WARDS_SUCCEEDED";
export const GET_WARDS_FAILED = "GET_WARDS_FAILED";

export const ADD_WARD_REQUESTED = "ADD_WARD_REQUESTED";
export const ADD_WARD_SUCCEEDED = "ADD_WARD_SUCCEEDED";
export const ADD_WARD_FAILED = "ADD_WARD_FAILED";

export const EDIT_WARD_REQUESTED = "EDIT_WARD_REQUESTED";
export const EDIT_WARD_SUCCEEDED = "EDIT_WARD_SUCCEEDED";
export const EDIT_WARD_FAILED = "EDIT_WARD_FAILED";

export const DELETE_WARD_REQUESTED = "DELETE_WARD_REQUESTED";
export const DELETE_WARD_SUCCEEDED = "DELETE_WARD_SUCCEEDED";
export const DELETE_WARD_FAILED = "DELETE_WARD_FAILED";

// Certificate
export const SET_CERTIFICATE = "SET_CERTIFICATE";

export const GET_CERTIFICATES_REQUESTED = "GET_CERTIFICATES_REQUESTED";
export const GET_CERTIFICATES_SUCCEEDED = "GET_CERTIFICATES_SUCCEEDED";
export const GET_CERTIFICATES_FAILED = "GET_CERTIFICATES_FAILED";

export const ADD_CERTIFICATE_REQUESTED = "ADD_CERTIFICATE_REQUESTED";
export const ADD_CERTIFICATE_SUCCEEDED = "ADD_CERTIFICATE_SUCCEEDED";
export const ADD_CERTIFICATE_FAILED = "ADD_CERTIFICATE_FAILED";

export const EDIT_CERTIFICATE_REQUESTED = "EDIT_CERTIFICATE_REQUESTED";
export const EDIT_CERTIFICATE_SUCCEEDED = "EDIT_CERTIFICATE_SUCCEEDED";
export const EDIT_CERTIFICATE_FAILED = "EDIT_CERTIFICATE_FAILED";

export const DELETE_CERTIFICATE_REQUESTED = "DELETE_CERTIFICATE_REQUESTED";
export const DELETE_CERTIFICATE_SUCCEEDED = "DELETE_CERTIFICATE_SUCCEEDED";
export const DELETE_CERTIFICATE_FAILED = "DELETE_CERTIFICATE_FAILED";
